version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"

volumes:
  pgdata: